### ISSUE TITLE
[Feature Request?] Easy leaving config screen

### ISSUE THREAD

**Issue by ThePhaseCat** [trainb0y/FabriHUD#3]
I didn't really know what to call this but uh would it be possible to make the config screen leavable with just pressing the escape key?
it's painful when i try to leave while pressing the escape key and it doesn't work

**Comment by trainb0y** [comment]
Yeah, this used to be how it worked, and is pretty easy to add back (like, one line of code type easy). 

The thing is I’m not sure whether it’s better to discard changes on escape, or to save them, so instead I just removed it entirely.  Which do you think is better?

**Comment by ThePhaseCat** [comment]
Maybe save them in case it's accidental?

**Comment by trainb0y** [comment]
Added with https://github.com/trainb0y/FabriHUD/commit/a0afde3c764a75b3d1f898ba3f8e7583a8061889

Leaving this issue open until release of the next version. I'll probably tweak a few things and release an update tomorrow.

**Comment by trainb0y** [comment]
Fixed in [v2.0.1](https://github.com/trainb0y/FabriHUD/releases/tag/v2.0.1)
