### ISSUE TITLE
[Bug] Opening the F3 menu doesn't remove the hud

### ISSUE THREAD

**Issue by ThePhaseCat** [trainb0y/FabriHUD#4]
I just started using a different F3 menu mod when I noticed that the hud from this mod doesn't disappear, not sure if this is intentional or not

**Comment by trainb0y** [comment]
Not intentional, I'll take a look and see if it's easy to disable when f3 is open.

**Comment by trainb0y** [comment]
Fixed with https://github.com/trainb0y/FabriHUD/commit/10c197906f7eab3b5cd8c49f14654cd5b6efc5fa
Will leaving this open until the next release, which will probably be later today.

**Comment by ThePhaseCat** [comment]
Ah that's great to hear👍

**Comment by trainb0y** [comment]
Fix included in [v2.0.1](https://github.com/trainb0y/FabriHUD/releases/tag/v2.0.1)
