### ISSUE TITLE
[QOL Feature?] Version Formating

### ISSUE THREAD

**Issue by ThePhaseCat** [trainb0y/FabriHUD#5]
More of a quality of life thing relating to different releases, but I personally think having actual version numbers might be a good way to differentiate between different updates. (Major numbers for feature additions and minor numbers for bug-fixes?)

I just now realized after looking at releases is that you did actually already have a release number tag, so maybe also put it in the title of releases? For addition clarity?

For example:

Initial Release could be v1.0
Kotlin and Text Shadow could v1.1 (Added features)
Minor fixes could be v1.1.1 (Bug fixes)

**Comment by trainb0y** [comment]
You mean for the GitHub releases?

**Comment by ThePhaseCat** [comment]
ah i see, yeah just in the title ig

**Comment by trainb0y** [comment]
Closing this, but I’ll try to make version numbers a little clearer in the future.

**Comment by ThePhaseCat** [comment]
Sounds good👍
